name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses
    
    - name: Install Android SDK components
      run: |
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653"
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Build debug APK
      run: ./gradlew assembleDebug
    
    - name: Build release APK
      run: ./gradlew assembleRelease
    
    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    
    - name: Upload release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk

  emulator-test:
    runs-on: macos-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses
    
    - name: Install Android SDK components
      run: |
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;25.2.9519653" "system-images;android-34;google_apis;x86_64"
    
    - name: Create AVD
      run: |
        echo "no" | avdmanager create avd -n test_avd -k "system-images;android-34;google_apis;x86_64" -d "pixel_5"
    
    - name: Start emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd test_avd -no-audio -no-window -no-boot-anim -gpu swiftshader_indirect &
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
    
    - name: Run instrumented tests
      run: ./gradlew connectedAndroidTest
    
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: app/build/reports/androidTests/connected/

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile
        push: false
        tags: android-dev:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max